1) A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.



In [79]:
import pandas as pd
import numpy as np
from scipy import stats
data=pd.read_csv('Cutlets.csv')

This is two sample t-test

H0:There is no significance in the diameter of the cutlet between two units.
H0: unitA-unitB=0

Ha:There is a significance in the diameter of the cutlet between two units.
Ha: unitA-unitB!=0

In [81]:
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [17]:
#checking for null values
data.isnull().sum()

Unit A    0
Unit B    0
dtype: int64

In [23]:
#checking for duplicates values
data[data.duplicated()].sum()

Unit A    0.0
Unit B    0.0
dtype: float64

In [16]:
#calculate two mean samles
stats.ttest_ind(data['Unit A'],data['Unit B'],alternative='two-sided')

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [26]:
#inferences at 5% significance level
pvalue=0.4722
alpha=0.05
if pvalue < 0.05:
    print('Reject null hypothesis')
else:
    print('Accept null hypothesis')
      

Accept null hypothesis


In [ ]:
Ans: There is no significance in the diameter of the cutlet between two units

2) A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) 
of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT 
for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.Analyze the data and determine 
whether there is any difference in average TAT among the different laboratories at 5% significance level.


In [ ]:
import pandas as pd
import numpy as np
from scipy import stats

This is Anova oneway (f-test)
     Ho: All  are lab samples means equal
     Ha: Atleast one lab sample is different

In [32]:
data=pd.read_csv('LabTAT.csv')

In [33]:
data

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [34]:
#By using Anova one way formula
stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [35]:
#5% significance level
pvalue=0 # p-value(2.1156708949992414e-57)almost 0
alpha=0.05
if pvalue < 0.05:
    print('Reject null hypothesis')
else:
    print('Accept null hypothesis')


Reject null hypothesis


Ans: There is a difference in the average Turn Around Time (TAT) of reports. 

3) Sales of products in four different regions is tabulated for males and females. 
Find if male-female buyer rations are similar across regions

In [55]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency

#This follows  chi-square test
Ho:All proportions are equal
H1: Not all proportions are equal

In [40]:
data=pd.read_csv('BuyerRatio.csv')

In [53]:
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [58]:
data1=data.iloc[:,1:]

In [59]:
data1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [60]:
data1.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [70]:
stat,P,dof,expected=chi2_contingency(data1)

In [71]:
expected

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [72]:
P

0.6603094907091882

In [73]:
dof

3

In [77]:
pvalue=0.660
alpha=0.05
if pvalue < 0.05:
     print('Dependent (reject H0)')
else:
    print('Independent (H0 holds true)')


Independent (H0 holds true)


Ans: Accept HO (All proportions are equal)

4) TeleCall uses 4 centers around the globe to process customer order forms. 
They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked 
before processing.The manager wants to check whether the defective %  varies by centre. 
Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency
data=pd.read_csv('customerorderform.csv')

In [ ]:
This follows chi-square test 
Ho: The defective % does not varies by centre ,variables are independent.
H1: The defective % varies by centre,variables are dependent there  is a relation.

In [3]:
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [5]:
data.columns

Index(['Phillippines', 'Indonesia', 'Malta', 'India'], dtype='object')

In [7]:
data['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [8]:
data['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [9]:
data['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [10]:
data['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [15]:
# Make a contingency table
observed_values=[[271,267,269,280],[29,33,31,20]]

In [16]:
from scipy.stats import chi2_contingency

In [18]:
# Chi2 contengency independence test
stats,P,dof,expected=chi2_contingency(observed_values)

In [19]:
P

0.2771020991233135

In [20]:
dof

3

In [21]:
expected

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [22]:
#At  5% significance level of significance
p_value=0.277
alpha=0.05
if p_value < alpha:
    print('variables are dependent there  is a relation')
else:
    print('variables are independent no relation')


variables are independent no relation


In [ ]:
Ans: Failed to reject the null hypothesis H0.